var  PLAY_CARD_ERROR = -1;
var  CARD_ATTACK_ERROR = -2;
var  COIN_NOT_ENOUGH = -100;
var  GEM_NOT_ENOUGH = -101;
var  NUMBER_CARD_NOT_ENOUGH = -102;
var CARD_NOT_FOUND = -103;
var CARD_LEVEL_NOT_CORRECT = -104;